const router = require('koa-router')();
const bookController = require('../../controllers/BookController/bookController');
router.prefix('/');
router.get('/queryAllBookList', bookController.getAllBookList);
router.post('/addNewBook', bookController.addNewBook);
router.post('/editBookInfoSubmit', bookController.editBookInfoSubmit);
router.post('/borrowBook', bookController.borrowBook);
router.post('/giveBackBook', bookController.giveBackBook);
router.post('/queryBorrowDetails', bookController.queryBorrowDetails);
router.get('/searchBorrowList', bookController.searchBorrowList);
router.post('/searchByBookName', bookController.searchByBookName);
module.exports = router;
